### ISSUE TITLE
Update Data

### ISSUE THREAD

**Issue by jxtngx** [shokru/mlfactor.github.io#75]
Feature request: please update the data to December 2022 and provide as a CSV or parquet file.

**Comment by shokru** [comment]
That would be great indeed, but sadly probably won't be possible. 
If you want more recent data, I recommend the one from Dacheng Xiu (from his _Empirical Asset Pricing Via Machine Learning paper_): https://dachxiu.chicagobooth.edu/download/datashare.zip
Which is great because the data is more massive.
You can forward short term momentum (mom1m) as dependent variable in this case.
It's the best I can advise...

**Comment by jxtngx** [comment]
thank you!
